name: Release Postgres

on:
  push:
    branches:
      - main
    paths:
      - "postgres/**"
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: google-github-actions/release-please-action@v3
        with:
          token: ${{ secrets.GH_PAT }}
          release-type: simple
          path: postgres/
          package-name: pg
          changelog-path: postgres/CHANGELOG.md
          monorepo-tags: true
